"""Office Lens ONNX document-processing adapter."""

from .adapter import (
    CLASSIFIER_LABELS,
    CLASSIFIER_MODEL,
    MODEL_DIR,
    PROCESSING_MODES,
    QUAD_MODEL,
    Classification,
    EnhancementResult,
    OfficeLensOnnx,
    PipelineResult,
    QuadMaskResult,
    detect_image_document_quad,
    enhance_document,
    enhance_page,
    enhance_photo,
    enhance_whiteboard,
    mask_to_quad,
    mode_from_classification,
    preprocess_classifier,
    preprocess_quad_mask,
    result_to_report,
    save_pipeline_outputs,
    warp_document_rgb,
)

__all__ = [
    "CLASSIFIER_LABELS",
    "CLASSIFIER_MODEL",
    "MODEL_DIR",
    "PROCESSING_MODES",
    "QUAD_MODEL",
    "Classification",
    "EnhancementResult",
    "OfficeLensOnnx",
    "PipelineResult",
    "QuadMaskResult",
    "detect_image_document_quad",
    "enhance_document",
    "enhance_page",
    "enhance_photo",
    "enhance_whiteboard",
    "mask_to_quad",
    "mode_from_classification",
    "preprocess_classifier",
    "preprocess_quad_mask",
    "result_to_report",
    "save_pipeline_outputs",
    "warp_document_rgb",
]
