"""Generate the deterministic MIT-licensed geometry regression corpus."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import cv2
import numpy as np


def _text_page() -> np.ndarray:
    image = np.full((720, 520, 3), 255, dtype=np.uint8)
    for index, text in enumerate(
        (
            "Document page",
            "quickly aligns",
            "baseline glyphs",
            "properly oriented",
            "local processing",
            "keeps text safe",
            "without any OCR",
        )
    ):
        cv2.putText(
            image,
            text,
            (35, 100 + index * 75),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.85,
            (0, 0, 0),
            2,
            cv2.LINE_AA,
        )
    return image


def _wave_page(amplitude: float) -> np.ndarray:
    height, width = 700, 900
    image = np.full((height, width, 3), 255, dtype=np.uint8)
    for baseline in range(90, 620, 65):
        for x in range(60, 840, 22):
            normalized_x = (2.0 * x / (width - 1)) - 1.0
            displacement = int(round(amplitude * (normalized_x**2 - 0.35)))
            cv2.rectangle(
                image,
                (x, baseline + displacement),
                (x + 12, baseline + displacement + 11),
                (0, 0, 0),
                -1,
            )
    return image


def _write(path: Path, image: np.ndarray) -> None:
    ok, encoded = cv2.imencode(".png", image)
    if not ok:
        raise RuntimeError(f"Cannot encode {path}")
    encoded.tofile(str(path))


def generate(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    upright = _text_page()
    images = {
        "upright.png": upright,
        "sideways-cw.png": cv2.rotate(upright, cv2.ROTATE_90_CLOCKWISE),
        "upside-down.png": cv2.rotate(upright, cv2.ROTATE_180),
        "sideways-ccw.png": cv2.rotate(upright, cv2.ROTATE_90_COUNTERCLOCKWISE),
        "curved.png": _wave_page(18.0),
        "straight.png": _wave_page(0.0),
    }
    matrix = cv2.getRotationMatrix2D((260, 360), 8.0, 1.0)
    images["skewed.png"] = cv2.warpAffine(
        upright,
        matrix,
        (520, 720),
        flags=cv2.INTER_LINEAR,
        borderValue=(255, 255, 255),
    )
    sparse = np.full((500, 360, 3), 255, dtype=np.uint8)
    cv2.rectangle(sparse, (130, 180), (230, 280), (30, 30, 30), 4)
    images["sparse.png"] = sparse
    yy, xx = np.indices((480, 640))
    photo = np.stack(
        ((xx % 256), (yy % 256), ((xx + yy) % 256)),
        axis=2,
    ).astype(np.uint8)
    cv2.circle(photo, (320, 240), 110, (40, 180, 220), -1)
    images["photo.png"] = photo
    images["blank.png"] = np.full((500, 360, 3), 255, dtype=np.uint8)
    for name, image in images.items():
        _write(output_dir / name, image)

    manifest = {
        "schemaVersion": 1,
        "corpusVersion": "1.0.0",
        "license": "MIT; generated by scripts/generate_geometry_corpus.py",
        "cases": [
            {"id": "upright", "image": "upright.png", "expectedOrientationAngle": 0},
            {"id": "sideways-cw", "image": "sideways-cw.png", "expectedOrientationAngle": 270},
            {"id": "upside-down", "image": "upside-down.png", "expectedOrientationAngle": 180},
            {"id": "sideways-ccw", "image": "sideways-ccw.png", "expectedOrientationAngle": 90},
            {
                "id": "skewed",
                "image": "skewed.png",
                "expectedDeskewAngle": -8.0,
                "deskewTolerance": 1.5,
            },
            {
                "id": "curved",
                "image": "curved.png",
                "dewarpExpectation": "apply",
                "minCurvatureImprovementRatio": 0.5,
            },
            {"id": "straight", "image": "straight.png", "dewarpExpectation": "noop"},
            {
                "id": "sparse",
                "image": "sparse.png",
                "expectedOrientationAngle": 0,
                "dewarpExpectation": "noop",
            },
            {
                "id": "photo",
                "image": "photo.png",
                "expectedOrientationAngle": 0,
                "dewarpExpectation": "noop",
            },
            {
                "id": "blank",
                "image": "blank.png",
                "expectedOrientationAngle": 0,
                "dewarpExpectation": "noop",
            },
        ],
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("benchmarks/geometry_v1"))
    args = parser.parse_args()
    generate(args.output)


if __name__ == "__main__":
    main()
